In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available.")

GPU is available
Using GPU: Tesla T4


Creating a tensor

In [ ]:
#using empty, allocates memory and no value assigned in the space, the value shown is already present in the memory
a = torch.empty(2,3)

In [ ]:
#type check
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.1263, 0.1936, 0.7591],
        [0.9906, 0.7673, 0.0515]])

In [ ]:
#use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#using arange, 0-> starting number, 10->  ending number, 2 -> step count
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
#using linspace, 0 -> start, 10 -> end, 10 -> evenly spaced
torch.linspace(0, 10, 10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
#using eyem, identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#using full, generates 3x3 tensors of 5s
torch.full((3,3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor shape


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #same shape different values

tensor([[          166,             0,             0],
        [6506875454955,  206158430216,           171]])

In [ ]:
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype = torch.float32) #not working because X has all integers, rand generates float

tensor([[0.7835, 0.9667, 0.4546],
        [0.1293, 0.4654, 0.7435]])

Tensor Data Types

In [ ]:
x.dtype #knowing datatype

torch.int64

In [ ]:
#assign data type
torch.tensor([1,2,3], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

Mathematical Ops

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.0352, 0.1930],
        [0.6326, 0.5178]])

1. Scalar Ops

In [ ]:
# addition
x + 2

# subtraction

x - 2

#multiplication
x*3

#division
x/10

#int division
(x*100)//3

#mod
x%3

#power
x**2

tensor([[0.0012, 0.0372],
        [0.4001, 0.2681]])

2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.2738, 0.5743, 0.1898],
        [0.6561, 0.4154, 0.9276]])
tensor([[0.6764, 0.5844, 0.9039],
        [0.0039, 0.2515, 0.6865]])


In [ ]:
a + b

a - b

a * b

a/b

a**b

a%b



tensor([[0.2738, 0.5743, 0.1898],
        [0.0019, 0.1639, 0.2411]])

In [ ]:
c = torch.tensor([1,-2,3,-4])
c

tensor([ 1, -2,  3, -4])

In [ ]:
# abs
torch.abs(c)



tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)


tensor([-1,  2, -3,  4])

In [ ]:
#round
torch.round(c)

tensor([ 1, -2,  3, -4])

In [ ]:
#ceil
torch.ceil(c)

tensor([ 1, -2,  3, -4])

In [ ]:
#floor
torch.floor(c)

tensor([ 1, -2,  3, -4])

In [ ]:
#clamp
torch.clamp(c, min=2, max=3)

tensor([2, 2, 3, 2])

3. Reduction Operation

In [ ]:
d = torch.randint(size=(2,3), low=0, high = 10, dtype=torch.float32)
d

tensor([[3., 6., 2.],
        [3., 9., 5.]])

In [ ]:
# sum
torch.sum(d)

tensor(28)

In [ ]:
# sum along columns
torch.sum(d, dim=0)

tensor([ 8, 10, 10])

In [ ]:
# mean
torch.mean(d)

tensor(5.1667)

In [ ]:
# median
torch.median(d)

tensor(3.)

In [ ]:
# max and min
torch.max(d)
torch.min(d)

tensor(2.)

In [ ]:
# product
torch.prod(d)

tensor(4860.)

In [ ]:
# std deviation
torch.std(d)

tensor(2.5820)

In [ ]:
# variance
torch.var(d)

tensor(6.6667)

In [ ]:
# argmax (position of max item)
torch.argmax(d)


tensor(4)

In [ ]:
# argmin (position of min item)
torch.argmin(d)

tensor(2)

4. Matrix operations

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10)
f = torch.randint(size=(3,2), low = 0, high=10)

print(e)
print(f)

tensor([[1, 5, 9],
        [1, 8, 2]])
tensor([[3, 3],
        [9, 0],
        [0, 3]])


In [ ]:
# matrix multiplication
torch.matmul(e, f)

tensor([[48, 30],
        [75,  9]])

In [ ]:
# dot multiplication
vec1 = torch.tensor([1, 2])
vec2 = torch.tensor([3, 4])
torch.dot(vec1,vec2)

tensor(11)

In [ ]:
# transpose
e
torch.transpose(e, 0, 1)

tensor([[1, 1],
        [5, 8],
        [9, 2]])

In [ ]:
# determinant (works for square matrices)
g = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
g
torch.det(g)

tensor(-32.)

In [ ]:
# inverse
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h
torch.inverse(h)


tensor([[-7.1429e-02,  2.6190e-01, -4.7619e-02],
        [ 2.5000e-01, -2.5000e-01,  4.3082e-09],
        [-3.2143e-01,  1.7857e-01,  2.8571e-01]])

5. Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[5, 5, 0],
        [4, 8, 9]])
tensor([[0, 1, 9],
        [6, 5, 1]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j


tensor([[True, True, True],
        [True, True, True]])

6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[5, 1, 6],
        [9, 7, 7]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 0.0000, 1.7918],
        [2.1972, 1.9459, 1.9459]])

In [ ]:
# exp
torch.exp(k)

tensor([[1.4841e+02, 2.7183e+00, 4.0343e+02],
        [8.1031e+03, 1.0966e+03, 1.0966e+03]])

In [ ]:
# sqrt
torch.sqrt(k)


tensor([[2.2361, 1.0000, 2.4495],
        [3.0000, 2.6458, 2.6458]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.7311, 0.9975],
        [0.9999, 0.9991, 0.9991]])

In [ ]:
# softmax
l = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

torch.softmax(l, dim=0)

tensor([[0.8808, 0.2689, 0.9526],
        [0.1192, 0.7311, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[5, 1, 6],
        [9, 7, 7]])

Inplace Operation " _ " -> signifies inplace op

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.0684, 0.9430, 0.2218],
        [0.5520, 0.2029, 0.4367]])
tensor([[0.3194, 0.2582, 0.3304],
        [0.8656, 0.8593, 0.8038]])


In [ ]:
m + n # changes done are temporary

tensor([[0.3878, 1.2012, 0.5522],
        [1.4175, 1.0622, 1.2405]])

In [ ]:
m.add_(n) #changes done in m are permanent

tensor([[0.3878, 1.2012, 0.5522],
        [1.4175, 1.0622, 1.2405]])

In [ ]:
torch.relu(m)

tensor([[0.3878, 1.2012, 0.5522],
        [1.4175, 1.0622, 1.2405]])

In [ ]:
m.relu_()

tensor([[0.3878, 1.2012, 0.5522],
        [1.4175, 1.0622, 1.2405]])

Copying Tensors

In [ ]:
x = torch.rand(2,3)
y = x
print(x)
print(y)

tensor([[0.3168, 0.6790, 0.3324],
        [0.8018, 0.6948, 0.6642]])
tensor([[0.3168, 0.6790, 0.3324],
        [0.8018, 0.6948, 0.6642]])


In [ ]:
id(x)

140187074072400

In [ ]:
id(y)

140187074072400

Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
# tensor on GPU
z = torch.rand((2,3), device=device)
z

tensor([[0.5170, 0.4881, 0.2824],
        [0.5187, 0.4313, 0.1802]], device='cuda:0')

In [ ]:
x.to(device)
x

tensor([[0.3168, 0.6790, 0.3324],
        [0.8018, 0.6948, 0.6642]])

In [ ]:
z + 5

tensor([[5.5170, 5.4881, 5.2824],
        [5.5187, 5.4313, 5.1802]], device='cuda:0')

CPU vs GPU Processing Time

In [ ]:
import time
size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
results_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
results_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

print("Speedup: ", cpu_time/gpu_time)

Time on CPU:  15.1674 seconds
Time on GPU:  0.1177 seconds
Speedup:  128.89007727311406


Reshape Tensor

In [ ]:
a = torch.ones(4,4)
a


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.8814, 0.6776, 0.9384, 0.6024],
         [0.5425, 0.5617, 0.7212, 0.9438],
         [0.4421, 0.4815, 0.1379, 0.3496]],

        [[0.7737, 0.4199, 0.8393, 0.9915],
         [0.5385, 0.4889, 0.0110, 0.2180],
         [0.8736, 0.0809, 0.0764, 0.2899]]])

In [ ]:
# permute

b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
c = torch.rand(226,226,3) #typical image size when a model is trained through CNN
c

tensor([[[0.0819, 0.7723, 0.9041],
         [0.2859, 0.0496, 0.5069],
         [0.3811, 0.0074, 0.6225],
         ...,
         [0.4228, 0.0243, 0.1308],
         [0.0968, 0.1495, 0.2156],
         [0.5488, 0.9790, 0.6810]],

        [[0.4324, 0.0725, 0.2633],
         [0.1888, 0.3408, 0.0335],
         [0.0830, 0.4940, 0.3338],
         ...,
         [0.1079, 0.6702, 0.4100],
         [0.7207, 0.3513, 0.0395],
         [0.1489, 0.8691, 0.7161]],

        [[0.0893, 0.7326, 0.0136],
         [0.9973, 0.8725, 0.4715],
         [0.5268, 0.5757, 0.4601],
         ...,
         [0.1431, 0.0049, 0.4119],
         [0.5154, 0.6164, 0.2301],
         [0.0094, 0.1471, 0.7060]],

        ...,

        [[0.3021, 0.9379, 0.2706],
         [0.5734, 0.1007, 0.1906],
         [0.3991, 0.6735, 0.9210],
         ...,
         [0.1351, 0.0403, 0.0287],
         [0.6452, 0.2643, 0.6244],
         [0.3650, 0.6553, 0.7278]],

        [[0.8331, 0.4074, 0.5508],
         [0.4083, 0.4029, 0.9459],
         [0.

In [ ]:
# unsqueeze (adds a new position)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
# squeeze (removes positions)
c.squeeze(1).shape


torch.Size([226, 226, 3])

In [ ]:
import numpy as np

a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])